swagger: "2.0"

info:
  description: "Use the Device API to identify all available users with unattended Bot Runner licenses, or filter for users by name.
      
      
      All API calls must contain either an authentication token from Authentication API (generates JSON Web token) or a bearer token from OAuth services. You cannot use both together in an API.<br>      
    
      **Header:** `X-Authorization: <<authentication token>> or Authorization: Bearer <<bearer token>>`"
  version: "1.0.0"
  title: "Device API"

basePath: "/v1/devices"

schemes:
  - "http"
  - "https"

produces:
  - application/json

securityDefinitions:
  AccessToken:
    type: apiKey
    description: >
      **X-Authorization: _token_**
    name: X-Authorization
    in: header

security:
  - AccessToken: []

paths:
  
  /{id}:
    delete:
      summary: "Delete a device"
      description:
        Use this endpoint to delete a device. You must specify the device ID.
      parameters:
        - name: "id"
          in: "path"
          description: "ID of the device"
          required: true
          type: integer
          format: int64
      tags:
        - Device
      responses:
        '204':
          description: Return 'nocontent'
        '400':
          description: Bad Request.
          schema:
            $ref: '#/definitions/Error'
        '401':
          description: Authentication required.
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: Not Found.
          schema:
            $ref: '#/definitions/ErrorMessage'
        '500':
          description: Server error.
          schema:
            $ref: '#/definitions/Error'

  /runasusers/list:
    post:
      summary: "List available run as users"
      description: "Use this endpoint to retrieve a list of available users with unattended Bot Runner licenses. This endpoint returns an user id, which is a numeric value that is used by APIs to identify users. You must be assigned a custom role that is associated with a Run As user device."
      tags:
        - Device
      consumes:
        - "application/json"
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/FilterRequest'
      responses:
        '200':
          description: >-
            Returns list of run as users available to the user
          schema:
            $ref: '#/definitions/DeviceRunAsUserResponse'
        '400':
          description: Bad Request.
          schema:
            $ref: '#/definitions/Error'
        '401':
          description: Authentication required.
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: Not Found.
          schema:
            $ref: '#/definitions/ErrorMessage'
        '500':
          description: Server error.
          schema:
            $ref: '#/definitions/Error'

  /runasusers/default:
    post:
      summary: "Assign default deployment device"
      description:
        Use this endpoint to set a specific device as the default deployment device for the specific user. You must have User management rights or admin rights.
      tags:
        - Device
      consumes:
        - "application/json"
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/RunAsUserDefaultDevice'
      responses:
        '200':
          description: >-
            Returns the details of the default device that was set for the user
          schema:
            $ref: '#/definitions/RunAsUserDefaultDevice'
        '400':
          description: Bad Request.
          schema:
            $ref: '#/definitions/Error'
        '401':
          description: Authentication required.
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: Not Found.
          schema:
            $ref: '#/definitions/ErrorMessage'
        '500':
          description: Server error.
          schema:
            $ref: '#/definitions/Error'

  /runasusers/default/unset:
    post:
      summary: "Unset the default deployment device"
      description:
        Use this endpoint to unset a specific device as the default deployment device for the specific user.
      
        - Only userId is a required parameter.
      
        -  deviceId value will be ignored.
      tags:
        - Device
      consumes:
        - "application/json"
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/RunAsUserDefaultDevice'
      responses:
        '200':
          description: >-
            Returns an empty response
        '400':
          description: Bad Request.
          schema:
            $ref: '#/definitions/Error'
        '401':
          description: Authentication required.
          schema:
            $ref: '#/definitions/Error'
        '404':
          description: Not Found.
          schema:
            $ref: '#/definitions/ErrorMessage'
        '500':
          description: Server error.
          schema:
            $ref: '#/definitions/Error'


definitions:

  Sort:
    type: object
    description: By default, search results are sorted in descending order with respect to their IDs. An alternative sorting is specified by using the sort query parameter.
    properties:
      field:
        type: string
        description: Field name to sort by
        example: username
      direction:
        type: string
        description: Sorting direction
        enum:
          - asc
          - desc

  PageRequest:
    type: object
    description: Pagination rules
    properties:
      offset:
        type: integer
        description: Page starting index
      length:
        type: integer
        description: Page length
        example: 100

  Filter:
    type: object
    description: Filter rules
    properties:
      operator:
        type: string
        description: Operator
        enum:
          - NONE
          - lt
          - le
          - eq
          - ne
          - ge
          - gt
          - substring
          - and
          - or
          - not
      operands:
        type: array
        items:
          $ref: '#/definitions/Filter'
        example:
          operator: substring
          field: id
          value: 9
      field:
        type: string
        description: Filter field
        example: name
      value:
        type: string
        description: Filter value
        example: bot

  FilterRequest:
    type: object
    description: 'Filter request, which includes filtering, sorting and pagination rules'
    properties:
      filter:
        $ref: '#/definitions/Filter'
      sort:
        type: array
        description: Sort directions
        items:
          $ref: '#/definitions/Sort'
      page:
        $ref: '#/definitions/PageRequest'

  DeviceRunAsUserResponse:
    type: "object"
    properties:
      page:
        type: "object"
        properties:
          offset:
            type: integer
          total:
            type: integer
            example: 6
          totalFilter:
            type: integer
            example: 6
      list:
        type: array
        items:
          $ref: '#/definitions/DeviceRunAsUser'

  DeviceRunAsUser:
    type: "object"
    properties:
      id:
        type: integer
        description: ID of the user
        example: 9
      username:
        type: string
        description: User name associated with the user
        example: ubr01_rt
      device:
        type: string
        description: Default device name attached to the user if availble. Else the device is "Picked at run time".
        example: DESKTOP-DBO6SIE
      deviceId:
        type: integer
        description: ID of the device if available. Else -1 is displayed.
        example: 3

  RunAsUserDefaultDevice:
    type: object
    properties:
      deviceId:
        type: integer
        description: ID of the device to be set as the default device for the users.
        example: 1046
      userId:
        type: integer
        description: ID of the user whose default device is being set.
        example: 589

  ErrorMessage:
    type: object
    properties:
      message:
        type: string
        description: Error Message

  Error:
    type: object
    properties:
      code:
        type: string
        description: Error code
      message:
        type: string
        description: Error Message